id: IDB590929
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T08:26:38+00:00'
last_modified: '2022-06-10T05:45:36.669499+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN7741
  title: བོད་ཀྱི་མི་སྣ་གྲགས་ཅན་གྱི་གཏམ་རྒྱུད། ༼༡༽
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    F922:
      image_group_id: I1KG26427
      title: Volume 1 of bod kyi mi sna grags can gyi gtam rgyud/ (1)
      total_pages: 100
      order: 1
      base_file: F922.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
